// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: internal/proto/cycle.proto

package endoflife_server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Base messages
type Cycle struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Cycle           string                 `protobuf:"bytes,1,opt,name=cycle,proto3" json:"cycle,omitempty"`
	ReleaseDate     string                 `protobuf:"bytes,2,opt,name=releaseDate,proto3" json:"releaseDate,omitempty"`
	Eol             string                 `protobuf:"bytes,3,opt,name=eol,proto3" json:"eol,omitempty"`
	Latest          string                 `protobuf:"bytes,4,opt,name=latest,proto3" json:"latest,omitempty"`
	Link            string                 `protobuf:"bytes,5,opt,name=link,proto3" json:"link,omitempty"`
	Lts             string                 `protobuf:"bytes,6,opt,name=lts,proto3" json:"lts,omitempty"`
	Support         string                 `protobuf:"bytes,7,opt,name=support,proto3" json:"support,omitempty"`
	Discontinued    string                 `protobuf:"bytes,8,opt,name=discontinued,proto3" json:"discontinued,omitempty"`
	ExtendedSupport string                 `protobuf:"bytes,9,opt,name=extendedSupport,proto3" json:"extendedSupport,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Cycle) Reset() {
	*x = Cycle{}
	mi := &file_internal_proto_cycle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cycle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cycle) ProtoMessage() {}

func (x *Cycle) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_cycle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cycle.ProtoReflect.Descriptor instead.
func (*Cycle) Descriptor() ([]byte, []int) {
	return file_internal_proto_cycle_proto_rawDescGZIP(), []int{0}
}

func (x *Cycle) GetCycle() string {
	if x != nil {
		return x.Cycle
	}
	return ""
}

func (x *Cycle) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *Cycle) GetEol() string {
	if x != nil {
		return x.Eol
	}
	return ""
}

func (x *Cycle) GetLatest() string {
	if x != nil {
		return x.Latest
	}
	return ""
}

func (x *Cycle) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Cycle) GetLts() string {
	if x != nil {
		return x.Lts
	}
	return ""
}

func (x *Cycle) GetSupport() string {
	if x != nil {
		return x.Support
	}
	return ""
}

func (x *Cycle) GetDiscontinued() string {
	if x != nil {
		return x.Discontinued
	}
	return ""
}

func (x *Cycle) GetExtendedSupport() string {
	if x != nil {
		return x.ExtendedSupport
	}
	return ""
}

type Language struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Language) Reset() {
	*x = Language{}
	mi := &file_internal_proto_cycle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Language) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Language) ProtoMessage() {}

func (x *Language) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_cycle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Language.ProtoReflect.Descriptor instead.
func (*Language) Descriptor() ([]byte, []int) {
	return file_internal_proto_cycle_proto_rawDescGZIP(), []int{1}
}

func (x *Language) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_proto_cycle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_cycle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_proto_cycle_proto_rawDescGZIP(), []int{2}
}

// Requests
type DetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailsRequest) Reset() {
	*x = DetailsRequest{}
	mi := &file_internal_proto_cycle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailsRequest) ProtoMessage() {}

func (x *DetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_cycle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailsRequest.ProtoReflect.Descriptor instead.
func (*DetailsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_cycle_proto_rawDescGZIP(), []int{3}
}

func (x *DetailsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DetailsRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Responses
type AllLanguagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Languages     []*Language            `protobuf:"bytes,1,rep,name=languages,proto3" json:"languages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllLanguagesResponse) Reset() {
	*x = AllLanguagesResponse{}
	mi := &file_internal_proto_cycle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllLanguagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllLanguagesResponse) ProtoMessage() {}

func (x *AllLanguagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_cycle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllLanguagesResponse.ProtoReflect.Descriptor instead.
func (*AllLanguagesResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_cycle_proto_rawDescGZIP(), []int{4}
}

func (x *AllLanguagesResponse) GetLanguages() []*Language {
	if x != nil {
		return x.Languages
	}
	return nil
}

var File_internal_proto_cycle_proto protoreflect.FileDescriptor

var file_internal_proto_cycle_proto_rawDesc = string([]byte{
	0x0a, 0x1a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xf7, 0x01, 0x0a, 0x05, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x79,
	0x63, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x44, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73,
	0x65, 0x44, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x65, 0x6f, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x74, 0x65, 0x73,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c,
	0x69, 0x6e, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x74, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6c, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x22, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x65, 0x64, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e,
	0x75, 0x65, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x53,
	0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x65, 0x78,
	0x74, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x1e, 0x0a,
	0x08, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x07, 0x0a,
	0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x3e, 0x0a, 0x0e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x45, 0x0a, 0x14, 0x41, 0x6c, 0x6c, 0x4c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d,
	0x0a, 0x09, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x52, 0x09, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x32, 0xb2, 0x01,
	0x0a, 0x0c, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x73, 0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x6c, 0x6c, 0x4c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x0f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x1a,
	0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x30, 0x01, 0x12,
	0x31, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x15, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x79, 0x63,
	0x6c, 0x65, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x72, 0x63, 0x73, 0x6f, 0x6c, 0x69, 0x73, 0x2f, 0x65, 0x6e, 0x64, 0x6f, 0x66, 0x6c, 0x69,
	0x66, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_internal_proto_cycle_proto_rawDescOnce sync.Once
	file_internal_proto_cycle_proto_rawDescData []byte
)

func file_internal_proto_cycle_proto_rawDescGZIP() []byte {
	file_internal_proto_cycle_proto_rawDescOnce.Do(func() {
		file_internal_proto_cycle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_cycle_proto_rawDesc), len(file_internal_proto_cycle_proto_rawDesc)))
	})
	return file_internal_proto_cycle_proto_rawDescData
}

var file_internal_proto_cycle_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_proto_cycle_proto_goTypes = []any{
	(*Cycle)(nil),                // 0: proto.Cycle
	(*Language)(nil),             // 1: proto.Language
	(*Empty)(nil),                // 2: proto.Empty
	(*DetailsRequest)(nil),       // 3: proto.DetailsRequest
	(*AllLanguagesResponse)(nil), // 4: proto.AllLanguagesResponse
}
var file_internal_proto_cycle_proto_depIdxs = []int32{
	1, // 0: proto.AllLanguagesResponse.languages:type_name -> proto.Language
	2, // 1: proto.CycleService.GetAllLanguages:input_type -> proto.Empty
	1, // 2: proto.CycleService.GetAllVersions:input_type -> proto.Language
	3, // 3: proto.CycleService.GetDetails:input_type -> proto.DetailsRequest
	4, // 4: proto.CycleService.GetAllLanguages:output_type -> proto.AllLanguagesResponse
	0, // 5: proto.CycleService.GetAllVersions:output_type -> proto.Cycle
	0, // 6: proto.CycleService.GetDetails:output_type -> proto.Cycle
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_cycle_proto_init() }
func file_internal_proto_cycle_proto_init() {
	if File_internal_proto_cycle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_cycle_proto_rawDesc), len(file_internal_proto_cycle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_cycle_proto_goTypes,
		DependencyIndexes: file_internal_proto_cycle_proto_depIdxs,
		MessageInfos:      file_internal_proto_cycle_proto_msgTypes,
	}.Build()
	File_internal_proto_cycle_proto = out.File
	file_internal_proto_cycle_proto_goTypes = nil
	file_internal_proto_cycle_proto_depIdxs = nil
}
